# Managed by modulesync
# Configs https://github.com/Mylezeem/mylezeem-msync
#
---
language: ruby
bundler_args: --without system_tests
script: <%= @configs['script'] %>
sudo: false
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
  allow_failures:
<% @configs['allow_failures'].each do |allowed_failure| -%>
  - rvm: <%= allowed_failure['rvm'] %>
    env: <%= allowed_failure['env'] %>
<% end -%>
notifications:
  email: false
